/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test.pb-c.h"
void   search_request__init
                     (SearchRequest         *message)
{
  static const SearchRequest init_value = SEARCH_REQUEST__INIT;
  *message = init_value;
}
size_t search_request__get_packed_size
                     (const SearchRequest *message)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t search_request__pack
                     (const SearchRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t search_request__pack_to_buffer
                     (const SearchRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SearchRequest *
       search_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SearchRequest *)
     protobuf_c_message_unpack (&search_request__descriptor,
                                allocator, len, data);
}
void   search_request__free_unpacked
                     (SearchRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &search_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor search_request__field_descriptors[3] =
{
  {
    "query",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, query),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_number",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, page_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result_per_page",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, result_per_page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned search_request__field_indices_by_name[] = {
  1,   /* field[1] = page_number */
  0,   /* field[0] = query */
  2,   /* field[2] = result_per_page */
};
static const ProtobufCIntRange search_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor search_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SearchRequest",
  "SearchRequest",
  "SearchRequest",
  "",
  sizeof(SearchRequest),
  3,
  search_request__field_descriptors,
  search_request__field_indices_by_name,
  1,  search_request__number_ranges,
  (ProtobufCMessageInit) search_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
