/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

#ifndef PROTOBUF_C_test_2eproto__INCLUDED
#define PROTOBUF_C_test_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SearchRequest SearchRequest;


/* --- enums --- */


/* --- messages --- */

struct  _SearchRequest
{
  ProtobufCMessage base;
  char *query;
  int32_t page_number;
  int32_t result_per_page;
};
#define SEARCH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&search_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0 }


/* SearchRequest methods */
void   search_request__init
                     (SearchRequest         *message);
size_t search_request__get_packed_size
                     (const SearchRequest   *message);
size_t search_request__pack
                     (const SearchRequest   *message,
                      uint8_t             *out);
size_t search_request__pack_to_buffer
                     (const SearchRequest   *message,
                      ProtobufCBuffer     *buffer);
SearchRequest *
       search_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   search_request__free_unpacked
                     (SearchRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SearchRequest_Closure)
                 (const SearchRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor search_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_test_2eproto__INCLUDED */
